/**
 * Sitemap generator.
 *
 * Reads the content modules as text, pulls every `slug:` out of them, and emits
 * `public/sitemap.xml`. Runs automatically before `npm run build`.
 *
 * Keeping this as a codegen step means a new case study or article shows up in
 * the sitemap as soon as it has a slug — no second list to maintain by hand.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SITE_URL = (process.env.VITE_SITE_URL ?? 'https://www.trisentri.ai').replace(/\/$/, '');

/** Routes that exist but are not generated from a slug list. */
const STATIC_ROUTES = [
  { path: '/', priority: '1.0', changefreq: 'weekly' },
  { path: '/solutions', priority: '0.9', changefreq: 'monthly' },
  { path: '/technologies', priority: '0.8', changefreq: 'monthly' },
  { path: '/industries', priority: '0.8', changefreq: 'monthly' },
  { path: '/products', priority: '0.8', changefreq: 'monthly' },
  { path: '/case-studies', priority: '0.8', changefreq: 'monthly' },
  { path: '/insights', priority: '0.8', changefreq: 'weekly' },
  { path: '/company', priority: '0.7', changefreq: 'monthly' },
  { path: '/contact', priority: '0.9', changefreq: 'yearly' },
];

/** Collections whose entries each expose a top-level `slug` property. */
const COLLECTIONS = [
  { file: 'src/data/solutions.ts', base: '/solutions', priority: '0.8', changefreq: 'monthly' },
  { file: 'src/data/caseStudies.ts', base: '/case-studies', priority: '0.7', changefreq: 'monthly' },
  { file: 'src/data/articles.ts', base: '/insights', priority: '0.7', changefreq: 'monthly' },
];

const SLUG_PATTERN = /^\s*slug:\s*'([^']+)'/gm;

function escapeXml(value) {
  return value.replace(/[<>&'"]/g, (char) => {
    switch (char) {
      case '<':
        return '&lt;';
      case '>':
        return '&gt;';
      case '&':
        return '&amp;';
      case "'":
        return '&apos;';
      default:
        return '&quot;';
    }
  });
}

function extractSlugs(source) {
  return [...source.matchAll(SLUG_PATTERN)].map((match) => match[1]);
}

const routes = [...STATIC_ROUTES];

for (const collection of COLLECTIONS) {
  const source = await readFile(resolve(ROOT, collection.file), 'utf8');
  const slugs = [...new Set(extractSlugs(source))];

  for (const slug of slugs) {
    routes.push({
      path: `${collection.base}/${slug}`,
      priority: collection.priority,
      changefreq: collection.changefreq,
    });
  }

  console.log(`  ${collection.base}: ${slugs.length} route(s)`);
}

const lastmod = new Date().toISOString().slice(0, 10);

const body = routes
  .map(
    (route) => `  <url>
    <loc>${escapeXml(`${SITE_URL}${route.path}`)}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${route.changefreq}</changefreq>
    <priority>${route.priority}</priority>
  </url>`,
  )
  .join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs - do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

await mkdir(resolve(ROOT, 'public'), { recursive: true });
await writeFile(resolve(ROOT, 'public/sitemap.xml'), xml, 'utf8');

console.log(`\n✓ public/sitemap.xml — ${routes.length} URLs`);
